#!/bin/bash

set -e -x -u

GOOS=darwin GOARCH=amd64 go build -o kwt-darwin-amd64 ./cmd/...
GOOS=darwin GOARCH=arm64 go build -o kwt-darwin-arm64 ./cmd/...
GOOS=linux GOARCH=amd64 go build -o kwt-linux-amd64 ./cmd/...
GOOS=linux GOARCH=arm64 go build -o kwt-linux-arm64 ./cmd/...

shasum -a 256 ./kwt-*
