---
groups:
- name: default
  jobs:
  - unit-tests
  - e2e-tests

jobs:
- name: unit-tests
  plan:
  - get: kwt
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          version: trusty
      run:
        path: /bin/bash
        args:
        - gopath/src/github.com/k14s/kwt/ci/unit-tests.sh
      inputs:
      - name: kwt
        path: gopath/src/github.com/k14s/kwt

- name: e2e-tests
  serial: true
  plan:
  - get: e2e-tests-interval
    trigger: true
  - get: kwt
  - task: test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          version: xenial
      params:
        KUBECONFIG_CONTENTS: ((kubeconfig))
      run:
        path: /bin/bash
        args:
        - -c
        - |
          mkdir -p ~/.kube
          set +x
          echo "$KUBECONFIG_CONTENTS" > ~/.kube/config
          set -x
          ./gopath/src/github.com/k14s/kwt/ci/e2e-tests.sh
      inputs:
      - name: kwt
        path: gopath/src/github.com/k14s/kwt

resources:
- name: kwt
  type: git
  source:
    uri: git@github.com:k14s/kwt
    branch: master
    private_key: ((private_git_ssh_pull_key))

- name: e2e-tests-interval
  type: time
  source:
    interval: 30m
