#@ load("@ytt:data", "data")

image: sshd
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: sshd
  path: images/sshd
  docker:
    buildx:
      pull: true
      noCache: true
      rawOptions:
      - --platform=linux/amd64,linux/arm64
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: sshd
  newImage: #@ data.values.push_repo
